FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# 安裝系統相依
RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev


# 先只複製 requirements.txt
COPY requirements.txt .

# 安裝 pip 最新版
RUN pip install --upgrade pip

# 安裝 Python 套件（只有 requirements.txt 改變才會重新執行）
RUN pip install --no-cache-dir -r requirements.txt

# 再複製其他程式碼（修改程式碼不會重新安裝套件）
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
