"""remove old owner column

Revision ID: 074bc9025622
Revises: d7662b794b81
Create Date: 2025-11-20 01:34:21.852700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074bc9025622'
down_revision: Union[str, Sequence[str], None] = 'd7662b794b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'owners', ['owner'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
