"""add user_hotel_association

Revision ID: 1fcff17d7903
Revises: 3df4af8c6b4b
Create Date: 2025-11-07 16:37:45.653276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1fcff17d7903'
down_revision: Union[str, Sequence[str], None] = '3df4af8c6b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hotel_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hotel_id')
    )
    op.add_column('hotel_rooms', sa.Column('hotel_name', sa.String(length=100), nullable=True))
    op.drop_index('ix_hotel_rooms_hotel_Name', table_name='hotel_rooms')
    op.create_index(op.f('ix_hotel_rooms_hotel_name'), 'hotel_rooms', ['hotel_name'], unique=True)
    op.drop_column('hotel_rooms', 'user_id')
    op.drop_column('hotel_rooms', 'hotel_Name')
    op.drop_column('users', 'hotel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hotel_rooms', sa.Column('hotel_Name', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('hotel_rooms', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hotel_rooms_hotel_name'), table_name='hotel_rooms')
    op.create_index('ix_hotel_rooms_hotel_Name', 'hotel_rooms', ['hotel_Name'], unique=True)
    op.drop_column('hotel_rooms', 'hotel_name')
    op.drop_table('user_hotel_association')
    # ### end Alembic commands ###
