"""initial migration

Revision ID: 54abba4e8cbb
Revises: 
Create Date: 2025-11-14 08:52:16.029916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54abba4e8cbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_rooms_hotel_name'), 'hotel_rooms', ['hotel_name'], unique=True)
    op.create_index(op.f('ix_hotel_rooms_id'), 'hotel_rooms', ['id'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_owner_name'), 'owners', ['owner_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_hotel',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'hotel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands adjusted to check table existence before dropping ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    # Drop user_hotel or user_hotel_association if exists
    if 'user_hotel' in tables:
        op.drop_table('user_hotel')
    elif 'user_hotel_association' in tables:
        op.drop_table('user_hotel_association')
    
    # Drop users table and indexes if exists
    if 'users' in tables:
        try:
            op.drop_index(op.f('ix_users_username'), table_name='users')
        except:
            pass
        try:
            op.drop_index(op.f('ix_users_id'), table_name='users')
        except:
            pass
        try:
            op.drop_index(op.f('ix_users_email'), table_name='users')
        except:
            pass
        op.drop_table('users')
    
    # Drop owners table and indexes if exists
    if 'owners' in tables:
        try:
            op.drop_index(op.f('ix_owners_owner_name'), table_name='owners')
        except:
            pass
        try:
            op.drop_index(op.f('ix_owners_id'), table_name='owners')
        except:
            pass
        op.drop_table('owners')
    
    # Drop hotel_rooms table and indexes if exists
    if 'hotel_rooms' in tables:
        try:
            op.drop_index(op.f('ix_hotel_rooms_id'), table_name='hotel_rooms')
        except:
            pass
        try:
            op.drop_index(op.f('ix_hotel_rooms_hotel_name'), table_name='hotel_rooms')
        except:
            pass
        op.drop_table('hotel_rooms')
    # ### end Alembic commands ###
