"""add OwnerTable

Revision ID: 9a33e8673a01
Revises: 9524f0c7d81c
Create Date: 2025-11-14 03:22:36.017030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a33e8673a01'
down_revision: Union[str, Sequence[str], None] = '9524f0c7d81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_owner_name'), 'owners', ['owner_name'], unique=True)
    op.add_column('hotel_rooms', sa.Column('hotel_name', sa.String(length=100), nullable=True))
    op.drop_index('ix_hotel_rooms_hotel_Name', table_name='hotel_rooms')
    op.create_index(op.f('ix_hotel_rooms_hotel_name'), 'hotel_rooms', ['hotel_name'], unique=True)
    op.drop_column('hotel_rooms', 'user_id')
    op.drop_column('hotel_rooms', 'hotel_Name')
    op.alter_column('user_hotel', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_hotel', 'hotel_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('user_hotel_ibfk_2', 'user_hotel', type_='foreignkey')
    op.drop_constraint('user_hotel_ibfk_1', 'user_hotel', type_='foreignkey')
    op.create_foreign_key(None, 'user_hotel', 'hotel_rooms', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_hotel', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'hotel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_hotel', type_='foreignkey')
    op.drop_constraint(None, 'user_hotel', type_='foreignkey')
    op.create_foreign_key('user_hotel_ibfk_1', 'user_hotel', 'hotel_rooms', ['hotel_id'], ['id'])
    op.create_foreign_key('user_hotel_ibfk_2', 'user_hotel', 'users', ['user_id'], ['id'])
    op.alter_column('user_hotel', 'hotel_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_hotel', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('hotel_rooms', sa.Column('hotel_Name', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('hotel_rooms', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hotel_rooms_hotel_name'), table_name='hotel_rooms')
    op.create_index('ix_hotel_rooms_hotel_Name', 'hotel_rooms', ['hotel_Name'], unique=True)
    op.drop_column('hotel_rooms', 'hotel_name')
    op.drop_index(op.f('ix_owners_owner_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
