"""hotelFix

Revision ID: d7662b794b81
Revises: 6e8bec391d16
Create Date: 2025-11-19 07:37:22.439695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7662b794b81'
down_revision: Union[str, Sequence[str], None] = '6e8bec391d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_rooms', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_hotel_rooms_hotel_name'), table_name='hotel_rooms')
    op.create_index(op.f('ix_hotel_rooms_hotel_name'), 'hotel_rooms', ['hotel_name'], unique=False)
    op.drop_constraint(None, 'hotel_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'hotel_rooms', 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hotel_rooms', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_rooms', sa.Column('owner', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'hotel_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'hotel_rooms', 'owners', ['owner'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hotel_rooms_hotel_name'), table_name='hotel_rooms')
    op.create_index(op.f('ix_hotel_rooms_hotel_name'), 'hotel_rooms', ['hotel_name'], unique=1)
    op.drop_column('hotel_rooms', 'owner_id')
    # ### end Alembic commands ###
